In [4]:
import numpy as np

In [5]:
X = np.zeros((3,4))

In [6]:
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
X.dtype

dtype('float64')

In [8]:
X = np.ones((3,2))

In [9]:
X.dtype

dtype('float64')

In [10]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
X = np.full((2,3), 5) 

In [12]:
X

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
X = np.eye(5)

In [14]:
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
X = np.diag([10,20,30,50])

In [16]:
X

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 50]])

In [17]:
x = np.arange(10)

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.shape

(10,)

In [63]:
x.dtype

dtype('int64')

In [21]:
x.dtype

dtype('int64')

In [22]:
x = np.arange(4,10)

In [23]:
x

array([4, 5, 6, 7, 8, 9])

In [24]:
x = np.arange(1,14,3)

In [25]:
x

array([ 1,  4,  7, 10, 13])

In [26]:
x = np.linspace(0,25,10)

In [27]:
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [28]:
x = np.linspace(0,25)

In [29]:
x

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ])

In [30]:
x = np.linspace(0,25,10, endpoint = False)

In [31]:
x

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [32]:
x = np.arange(20)

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
x = np.reshape(x, (4,5))

In [35]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
Y = np.arange(20).reshape(4, 5)

In [37]:
Y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

In [39]:
X

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [40]:

X = np.random.random((3,3))

In [41]:
X

array([[0.18991178, 0.77771423, 0.44548363],
       [0.69663593, 0.21842149, 0.22549141],
       [0.24109397, 0.00350563, 0.46748495]])

In [42]:
X = np.random.randint(4,15,size=(3,2))

In [43]:
X

array([[10,  7],
       [ 6,  9],
       [ 9,  7]])

In [44]:
X = np.random.normal(0, 0.1, size=(1000,1000))

In [45]:
X

array([[ 0.24661282, -0.08330391,  0.02793653, ...,  0.05333206,
         0.04657711,  0.0094524 ],
       [-0.08316044, -0.05247732, -0.11678476, ...,  0.09169625,
        -0.04407613, -0.0939032 ],
       [-0.17169105, -0.11644059, -0.07276187, ...,  0.15846068,
         0.06146949, -0.04522694],
       ...,
       [ 0.15445267,  0.03107169, -0.02656091, ...,  0.08057174,
        -0.14447639,  0.10016758],
       [ 0.30173018,  0.07449813, -0.04569122, ...,  0.07609676,
        -0.11468529,  0.17227929],
       [ 0.03642808,  0.00113158,  0.0868589 , ..., -0.10532205,
        -0.00923801,  0.15498704]])

In [46]:
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

The elements in X are of type: float64
The elements in X have a mean of: -0.00012701181269577936
The maximum value in X is: 0.45093287166156576
The minimum value in X is: -0.4550227524855126
X has 501026 negative numbers
X has 498974 positive numbers


In [47]:
x = np.array([1, 2, 3, 4, 5])

In [48]:
x

array([1, 2, 3, 4, 5])

In [49]:
x = np.array([1,2,3,4,5])

In [50]:
print('This is First Element in x:', x[0]) 
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5



In [51]:
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


In [52]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [54]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
X[0,0] = 20

In [56]:
X

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [62]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [58]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [59]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
x = np.delete(x, [0,4])

In [61]:
x

array([2, 3, 4])

In [64]:
w = np.delete(Y, 0, axis=0)

In [65]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
w

array([[4, 5, 6],
       [7, 8, 9]])

In [67]:
v = np.delete(Y, [0,2], axis=1)

In [68]:
v

array([[2],
       [5],
       [8]])

In [69]:
x = np.array([1, 2, 3, 4, 5])

In [70]:
x

array([1, 2, 3, 4, 5])

In [71]:
Y = np.array([[1,2,3],[4,5,6]])

In [72]:
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
x = np.append(x, 6)

In [74]:
x

array([1, 2, 3, 4, 5, 6])

In [75]:
x = np.append(x, [7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
v = np.append(Y, [[7,8,9]], axis=0)

In [77]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
q = np.append(Y,[[9],[10]], axis=1)

In [79]:
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
q

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [83]:
q = np.append(Y,[[9],[10]], axis=1)

In [84]:
q

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 10]])

In [85]:
x = np.array([1, 2, 5, 6, 7])

In [86]:
x

array([1, 2, 5, 6, 7])

In [87]:
Y = np.array([[1,2,3],[7,8,9]])

In [90]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
x = np.insert(x,2,[3,4])

In [92]:
x

array([1, 2, 3, 4, 3, 4, 5, 6, 7])

In [93]:
w = np.insert(Y,1,[4,5,6],axis=0)

In [94]:
Y

array([[1, 2, 3],
       [7, 8, 9]])

In [95]:
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
v = np.insert(Y,1,5, axis=1)

In [97]:
v

array([[1, 5, 2, 3],
       [7, 5, 8, 9]])

In [98]:
x = np.array([1,2])

In [99]:
Y = np.array([[3,4],[5,6]])

In [102]:
x

array([1, 2])

In [103]:
Y

array([[3, 4],
       [5, 6]])

In [104]:
z = np.vstack((x,Y))

In [105]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
w = np.hstack((Y,x.reshape(2,1)))

In [107]:
w

array([[3, 4, 1],
       [5, 6, 2]])

In [109]:
X   = np.arange(20).reshape(4, 5)

In [110]:
x

array([1, 2])

In [111]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [112]:
Z = X[1:4,2:5]

In [113]:
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [114]:
W = X[1:,2:5]

In [115]:
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [116]:
Y = X[:3,2:5]

In [117]:
Y

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [118]:
v = X[2,:]

In [119]:
v

array([10, 11, 12, 13, 14])

In [120]:
q = X[:,2]

In [121]:
q

array([ 2,  7, 12, 17])

In [122]:
R = X[:,2:3]

In [123]:
R

array([[ 2],
       [ 7],
       [12],
       [17]])

In [124]:
Z = X[1:4,2:5]

In [125]:
X = np.arange(20).reshape(4, 5)

In [126]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [127]:
Z = X[1:4,2:5]

In [128]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [130]:
Z[2,2] = 555

In [131]:
X = np.arange(20).reshape(4, 5)

In [132]:
X = np.arange(20).reshape(4,5)

In [133]:
Z = np.copy(X[1:4,2:5])

In [134]:
Z

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [135]:
W = X[1:4,2:5].copy()

In [136]:
W

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [137]:
Z[2,2] = 555

In [138]:
W[2,2] = 444

In [139]:
Z

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 555]])

In [140]:
W

array([[  7,   8,   9],
       [ 12,  13,  14],
       [ 17,  18, 444]])

In [141]:
X = np.arange(20).reshape(4, 5)

In [142]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
indices = np.array([1,3])

In [144]:
indices

array([1, 3])

In [145]:
Y = X[indices,:]

In [146]:
Y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [147]:
Z = X[:, indices]

In [148]:
Z

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])

In [149]:
X = np.arange(25).reshape(5, 5)

In [150]:
print('z =', np.diag(X))

z = [ 0  6 12 18 24]


In [151]:
print('y =', np.diag(X, k=1))

y = [ 1  7 13 19]


In [152]:
print('w = ', np.diag(X, k=-1))

w =  [ 5 11 17 23]


In [153]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

In [154]:
X

array([[1, 2, 3],
       [5, 2, 8],
       [1, 2, 3]])

In [155]:
print('The unique elements in X are:',np.unique(X))

The unique elements in X are: [1 2 3 5 8]


In [156]:
X = np.arange(25).reshape(5, 5)

In [157]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
print('The elements in X that are greater than 10:', X[X > 10])

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [159]:
print('The elements in X that less than or equal to 7:', X[X <= 7])

The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]


In [160]:
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

The elements in X that are between 10 and 17: [11 12 13 14 15 16]


In [161]:
X[(X > 10) & (X < 17)] = -1

In [162]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [163]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [164]:
x = np.random.randint(1,11,size=(10,))

In [165]:
print('Sorted x (out of place):', np.sort(x))

Sorted x (out of place): [ 1  2  2  4  6  6  8  9  9 10]


In [166]:
print(np.sort(np.unique(x)))

[ 1  2  4  6  8  9 10]
